Added a summer school for this year
1ethanhansen/Quantum-Computing-Opportunities pull request #7
Opened 2020-05-21 21:46 UTC by duarte-jfs

2020-05-21 23:28 UTC, 1ethanhansen requested changes

2020-05-21 23:28 UTC, 1ethanhansen commented on FEEDBACK.md
> +### Los Alamos Quantum Computing Summer School (ISTI)
This already exists in the repo, so this is creating a merge conflict. It looks like your fork is behind my master branch a bit. Either catch up your branch, then re-add the summer school, or you can just re-fork my repo and re-add the summer school

2020-05-21 23:28 UTC, 1ethanhansen commented on FEEDBACK.md
> +### QOSF Mentorship Program (Quantum Open Source Foundation)
This already exists in the repo, so this is creating a merge conflict. See above comment

2020-05-21 23:28 UTC, 1ethanhansen commented on FEEDBACK.md
> +### Summer School on Machine Learning and Big Data with Quantum Computing (University of Porto)
This lgtm :)

2020-05-21 23:28 UTC, 1ethanhansen commented on README.md
> +| Los Alamos Quantum Computing Summer School| [Info Page](https://www.lanl.gov/projects/national-security-education-center/information-science-technology/summer-schools/quantumcomputing/index.php) |
This already exists in the repo, so this is creating a merge conflict. See longer comment in FEEDBACK.md.

2020-05-21 23:28 UTC, 1ethanhansen commented on README.md
> +| QOSF Mentorship program | [Info Page](https://qosf.org/qc_mentorship/) | Quantum Open Source Foundation | Program runs in batches | ![closed status][closed] | [![FB][feedback]](FEEDBACK.md#qosf-men
This already exists in the repo, so this is creating a merge conflict. See longer comment in FEEDBACK.md.

2020-05-21 23:28 UTC, 1ethanhansen commented on README.md
> +| Summer School on Machine Learning and Big Data with Quantum Computing | [Info Page](https://smbq2020.dcc.fc.up.pt/) | University of Porto | September 7-8 2020 | ![open status][open] | [![FB][feedba
The link to FEEDBACK is wrong. Try going to FEEDBACK.md and clicking on the link button next to the header, then copypasting the last bit of the url that pops up in your browser

2020-05-21 23:43 UTC, duarte-jfs commented
I really have to look into how to work with github, I'll take a look at it tomorrow. I need to fix this, should have seen I was 5 commits behind

2020-05-22 00:25 UTC, 1ethanhansen commented
> 
> 
> I really have to look into how to work with github, I'll take a look at it tomorrow. I need to fix this, should have seen I was 5 commits behind

It's all good :+1: It's super cool you're learning. Feel free to shoot me an email at [1ethanhansen@protonmail.com](mailto:1ethanhansen@protonmail.com) if you want to walk through it with me, I'm always happy to help :)

2020-06-23 00:53 UTC, 1ethanhansen commented
Hi @duarte-jfs any updates on this? 😄

2020-06-23 09:20 UTC, closed without merging

2020-06-23 09:35 UTC, duarte-jfs commented
@1ethanhansen  Hi, yeah, you should have already an up to date pull request. Sorry for the delay, it completely slipped by me.